"""empty message

Revision ID: 4a7d72ca3323
Revises: 6e9c00b31925
Create Date: 2020-03-31 02:53:32.053355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a7d72ca3323'
down_revision = '6e9c00b31925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('openid', table_name='users')
    op.drop_column('users', 'openid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('openid', mysql.VARCHAR(length=128), nullable=False))
    op.create_index('openid', 'users', ['openid'], unique=True)
    # ### end Alembic commands ###
