"""empty message

Revision ID: 6e9c00b31925
Revises: 9952388519ce
Create Date: 2020-03-31 02:09:32.231410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9c00b31925'
down_revision = '9952388519ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('openid', sa.String(length=128), nullable=False))
    op.create_unique_constraint(None, 'users', ['openid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'openid')
    # ### end Alembic commands ###
